package com.example.isen.noroughapk.BDD.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by Thaddée on 28/10/2016.
 */

public class Partie extends RealmObject {

    @PrimaryKey
    private int id;
    private String datePartie;
    private int score1, score2,score3,score4,score5,score6,score7,score8,score9,score10,score11,score12,score13,score14,score15,score16,score17,score18;
    private String handicap;
    private String trou;
    private String score;
    private String parcour;
    private String meteoIcon;

    public String getMeteoIcon() {
        return meteoIcon;
    }

    public void setMeteoIcon(String meteoIcon) {
        this.meteoIcon = meteoIcon;
    }

    public String getParcour() {
        return parcour;
    }

    public void setParcour(String parcour) {
        this.parcour = parcour;
    }
    // Standard getters & setters generated by your IDE…

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDatePartie() {
        return datePartie;
    }

    public void setDatePartie(String datePartie) {
        this.datePartie = datePartie;
    }

    public String getHandicap() {
        return handicap;
    }

    public String getTrou() {
        return trou;
    }

    public void setHandicap(String handicap) {
        this.handicap = handicap;
    }

    public void setTrou(String trou) {
        this.trou = trou;
    }

    public int getScore1() {
        return score1;
    }

    public void setScore1(int score1) {
        this.score1 = score1;
    }

    public int getScore2() {
        return score2;
    }

    public int getScore3() {
        return score3;
    }

    public int getScore4() {
        return score4;
    }

    public int getScore5() {
        return score5;
    }

    public int getScore6() {
        return score6;
    }

    public int getScore7() {
        return score7;
    }

    public int getScore8() {
        return score8;
    }

    public int getScore9() {
        return score9;
    }

    public int getScore10() {
        return score10;
    }

    public int getScore11() {
        return score11;
    }

    public int getScore12() {
        return score12;
    }

    public int getScore13() {
        return score13;
    }

    public int getScore14() {
        return score14;
    }

    public int getScore15() {
        return score15;
    }

    public int getScore16() {
        return score16;
    }

    public int getScore17() {
        return score17;
    }

    public int getScore18() {
        return score18;
    }

    public void setScore2(int score2) {
        this.score2 = score2;
    }

    public void setScore3(int score3) {
        this.score3 = score3;
    }

    public void setScore4(int score4) {
        this.score4 = score4;
    }

    public void setScore5(int score5) {
        this.score5 = score5;
    }

    public void setScore6(int score6) {
        this.score6 = score6;
    }

    public void setScore7(int score7) {
        this.score7 = score7;
    }

    public void setScore8(int score8) {
        this.score8 = score8;
    }

    public void setScore9(int score9) {
        this.score9 = score9;
    }

    public void setScore10(int score10) {
        this.score10 = score10;
    }

    public void setScore11(int score11) {
        this.score11 = score11;
    }

    public void setScore12(int score12) {
        this.score12 = score12;
    }

    public void setScore13(int score13) {
        this.score13 = score13;
    }

    public void setScore14(int score14) {
        this.score14 = score14;
    }

    public void setScore15(int score15) {
        this.score15 = score15;
    }

    public void setScore16(int score16) {
        this.score16 = score16;
    }

    public void setScore17(int score17) {
        this.score17 = score17;
    }

    public void setScore18(int score18) {
        this.score18 = score18;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }
}